//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltenek.ConnectBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReltorsAgencyEntities : DbContext
    {
        public ReltorsAgencyEntities()
            : base("name=ReltorsAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Need> Need { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Realtor> Realtor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
