//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltenek.ConnectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int id_property { get; set; }
        public string type_property { get; set; }
        public int number_of_rooms { get; set; }
        public int number_of_floors { get; set; }
        public Nullable<int> floor_number { get; set; }
        public decimal price { get; set; }
        public double area { get; set; }
        public Nullable<int> id_photo { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
