//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltenek.ConnectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtor
    {
        public int id_realtor { get; set; }
        public string for_name { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public double coefficient { get; set; }
        public int amount_of_deals { get; set; }
        public Nullable<int> id_clients { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
